[package]
name = "ibsr-collector"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "IBSR XDP collector CLI"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
thiserror.workspace = true

[dev-dependencies]
