title: IBSR
remote_theme: just-the-docs/just-the-docs
logo: /null_rabbit_logo.webp

# Navigation order
nav_order: auto

# Search
search_enabled: true
search:
  heading_level: 3

# Footer
gh_edit_link: true
gh_edit_repository: https://github.com/NullRabbitLabs/nr-ibsr
gh_edit_branch: main
gh_edit_source: docs
gh_edit_view_mode: edit
